### PR TITLE
Add Delta time calculation.

### PR DESCRIPTION
**Pull request by LumpBloom7**
Will be useful during update functions and the like...

### CODE REVIEW

**Comment by LumpBloom7** [comment]
Will make `m_deltaTime` protected and create a getter function instead.

**Review by kasmacioma — DISMISSED** [review]
What about my implementation of timer https://github.com/xapdkop/BloomFramework/commit/1f2850e5b90103000374508ccc2d3d773ff35394?

**Comment by LumpBloom7** [comment]
Add yourself as a co author by adding this to the end of the commit message

`Co-authored-by: name <Git email>`

Keep the angle brackets around the email. You can use your GitHub noreply email if you want.

**Review by kasmacioma — APPROVED** [review]
Devs are the best. Good changes. Just wanted to suggest it heh.

**Pull request merged**
