### PR TITLE
Add basic functionality to framework

### PR DESCRIPTION
**Pull request by LumpBloom7**
We should start by adding the things necessary to make a game framework

### CODE REVIEW

**Comment by LumpBloom7** [comment]
Ignore the dupe code warning for now.

**Review by siew24 — APPROVED** [review]
A lot of basic initialization added, even though i haven't learned the basics of OpenGL :'). Now what is left is the game logic

**Review by siew24 — DISMISSED** [review]

**Review by siew24 — COMMENTED** [review]
Are we making a MapleStory-ish game?

**Comment by LumpBloom7** [comment]
Here's a footage of the Framework in action as of right now.
https://youtu.be/M5ANPG7wJ5c

@siew24 Discussions like that away from PR comments pls, Discord group or PM.

**Comment by siew24** [comment]
Good choice about Codacy...

**Comment by LumpBloom7** [comment]
Rebased onto master branch so AppVeyor.yml is present.
We now have automatic build testing!!

**Comment by LumpBloom7** [comment]
That totally fucked up this PR.

**Comment by LumpBloom7** [comment]
Here's a footage of the Framework in action as of right now.
https://youtu.be/Fv5MVLLK-Kg

**Comment by LumpBloom7** [comment]
Here's a footage of the Framework in action as of right now.
https://youtu.be/jcELbNYdAOA

KEYBOARD WORKS WOW!

**Comment by LumpBloom7** [comment]
Next up: Migrating game specific code to the Test Bench.🤞🤞

**Comment by LumpBloom7** [comment]
Trying to migrate entire ECS to use [EntityX](https://github.com/alecthomas/entityx). Will later try to build another myself if I deem it necessary.

**Pull request closed without merging**
