### PR TITLE
Migrate to Azure Pipelines from AppVeyor

### PR DESCRIPTION
**Pull request by LumpBloom7**
Azure Pipelines seems to provide more features, including parallel builds.

### CODE REVIEW

**Comment by kasmacioma** [comment]
@LumpBloom7 what about adding yaml config file for azure?

**Comment by LumpBloom7** [comment]
I tried, but I don't think I could get a full yaml config file for visual designer. I could only get the yaml for the Agent job, and even then it fails to get imported when I tried on my fork.

**Comment by kasmacioma** [comment]
Ok, i'll try to make it today or tomorrow

**Comment by kasmacioma** [comment]
Done

**Review by kasmacioma — APPROVED** [review]
Azure pipelines seems better then AppVeyor

**Pull request merged**
