### PR TITLE
Audio support

### PR DESCRIPTION
**Pull request by kasmacioma**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) **(docs? hahaha, pls no)**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Audio support (extended SDL_mixer implementation)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
I guess not. But it adds a bit of unrelated changes:
* new `update` function for TestBench>RandomizerSystem
* added `hideWindow` and `showWindow()` functions to Game

### CODE REVIEW

**Comment by kasmacioma** [comment]
@LumpBloom7 what do you think, should I keep the samples or it would be better to delete them?

**Comment by LumpBloom7** [comment]
Maybe remove the full samples. The short ones could stay. (For now)

**Comment by kasmacioma** [comment]
@LumpBloom7 done ;)

**Review by LumpBloom7 — APPROVED** [review]

**Comment by kasmacioma** [comment]
oh hug, my last commit didn't pull.

**Pull request merged**
