### PR TITLE
Texture related improvements

### PR DESCRIPTION
**Pull request by kasmacioma**
* Load `SDL_Texture` in `Texture()` ctor rather than in `TextureStore::load()`
* Use `std::filesystem::path` instead of `std::string`
* Get resources from executable directory rather than from the current directory
* Use post-build events to copy assets to the output directory

### CODE REVIEW

**Review by LumpBloom7 — DISMISSED** [review]
Makes sense.

**Comment by kasmacioma** [comment]
@LumpBloom7, pls build solution on your pc before pushing commits :|

**Comment by LumpBloom7** [comment]
Sorry 😅

**Comment by kasmacioma** [comment]
Pls, don't merge yet

**Comment by LumpBloom7** [comment]
> Pls, don't merge yet

Nah. Definitely not without your confirmation.

**Comment by kasmacioma** [comment]
@LumpBloom7 do you think we should merge this pr now?
```cpp
if (your_answer == "yes")
    addReview();
else
    suggestChanges();
```

**Review by LumpBloom7 — DISMISSED** [review]
Using `std::filesystem` is certainly better than just using a string.
And having post-build events are also good.
Approved!

**Comment by kasmacioma** [comment]
@LumpBloom7 I think now we're ready to merge this pr. Add pls ur review (again) ;)

**Review by LumpBloom7 — APPROVED** [review]
Good changes. Very necessary.

**Pull request merged**
