### PR TITLE
Add game object

### PR DESCRIPTION
**Pull request by LumpBloom7**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces `GameObject`s, which is a core part of game engines

* **Other information**:
A basic `MovementSystem` has been added for testing purposes.
Simple `Components` has been added.

### CODE REVIEW

**Comment by LumpBloom7** [comment]
I think this is ready to be pulled since I wanna focus on one thing at a time.
Further functionality will be added in future PRs.

**Comment by kasmacioma** [comment]
Hmmmmmm, @LumpBloom7, did you forget to do this?
https://github.com/BloomCreativeWorks/BloomFramework/blob/1dfe975ddcccbdcd9d92d8873c284aeae30e2036/BloomFramework/include/stdIncludes.h#L22

**Review by kasmacioma — DISMISSED** [review]
Needs small fixes.

**Comment by kasmacioma** [comment]
And is it necessary to require DeltaTime as it's not used in the function.
https://github.com/BloomCreativeWorks/BloomFramework/blob/1dfe975ddcccbdcd9d92d8873c284aeae30e2036/BloomFramework/include/Systems/RenderSystem.h#L11

https://github.com/BloomCreativeWorks/BloomFramework/blob/1dfe975ddcccbdcd9d92d8873c284aeae30e2036/BloomFramework/include/Systems/DefaultSystem.h#L10

**Comment by LumpBloom7** [comment]
> And is it necessary to require DeltaTime as it's not used in the function.
> [BloomFramework/BloomFramework/include/Systems/RenderSystem.h](https://github.com/BloomCreativeWorks/BloomFramework/blob/1dfe975ddcccbdcd9d92d8873c284aeae30e2036/BloomFramework/include/Systems/RenderSystem.h#L11)
> 
> Line 11 in [1dfe975](/BloomCreativeWorks/BloomFramework/commit/1dfe975ddcccbdcd9d92d8873c284aeae30e2036)
> 
>  void System::update(std::optional<DeltaTime> dt = std::nullopt) 
> [BloomFramework/BloomFramework/include/Systems/DefaultSystem.h](https://github.com/BloomCreativeWorks/BloomFramework/blob/1dfe975ddcccbdcd9d92d8873c284aeae30e2036/BloomFramework/include/Systems/DefaultSystem.h#L10)
> 
> Line 10 in [1dfe975](/BloomCreativeWorks/BloomFramework/commit/1dfe975ddcccbdcd9d92d8873c284aeae30e2036)
> 
>  virtual void update(std::optional<DeltaTime> deltaTime = std::nullopt) = 0;


I'm planning to have `Screen`s update every system by itself whenever `game->update()` is called.

Kinda like this.
```cpp
void Screen::update(){
	for(auto i : systems)
		i.update(dt);
}
```

So having `System`s that have different `update()` functions is not ideal. I'm thinking that DeltaTime will always be passed in and the function definition can ignore the DT if it is not required.

**Comment by LumpBloom7** [comment]
> Hmmmmmm, @LumpBloom7, did you forget to do this?
> [BloomFramework/BloomFramework/include/stdIncludes.h](https://github.com/BloomCreativeWorks/BloomFramework/blob/1dfe975ddcccbdcd9d92d8873c284aeae30e2036/BloomFramework/include/stdIncludes.h#L22)
> 
> Line 22 in [1dfe975](/BloomCreativeWorks/BloomFramework/commit/1dfe975ddcccbdcd9d92d8873c284aeae30e2036)
> 
>  typedef double DeltaTime; // Remove this before merging.

Sorta, I was planning on merging DT_Improvements to master, which didn't happen.

**Comment by siew24** [comment]
It should have a memory limit too, just in case if anyone's PC doesn't have enough allocated memory to do so

**Review by kasmacioma — APPROVED** [review]
It seems that there are no critical bugs. Let's see how it will work.

**Pull request merged**
