### PR TITLE
Code rework

### PR DESCRIPTION
**Pull request by kasmacioma**

### CODE REVIEW

**Review by LumpBloom7 — DISMISSED** [review]
All looks good here. 
Should we mind the CodeFactor issues, particularly the one about `rand_s()`?

**Comment by kasmacioma** [comment]
Lol, ```rand_r()```? It seems that this function has been removed from the ```stdlib.h```. Also ```rand()``` uses only for generate color in Test Bench. So you can ignore it.

**Comment by LumpBloom7** [comment]
Then CodeFactor must be drunk...

**Review by LumpBloom7 — APPROVED** [review]
Then CodeFactor must be drunk...

Guess this is okay then. Merging this.

**Pull request merged**
