### PR TITLE
Some optimisations and fixes

### PR DESCRIPTION
**Pull request by kasmacioma**
### Changes:
- improved error messages
- added support of the latest sdl2-nuget packages
- removed junk from .vcxproj.filters files (see "what is this?" and "what is this? [2]")

### CODE REVIEW

**Comment by LumpBloom7** [comment]
@xapdkop,
Thanks for helping with my issue. I appreciate it.

Was the problem with the Nuget package an issue on your end or was it because of my stupidity?

This solves my problems with the Nuget packages and should be good to merge.

PS: I'm surprised you found the exact project I'm working on. :)

**Review by LumpBloom7 — DISMISSED** [review]
@xapdkop,
Thanks for helping with my issue. I appreciate it.

Was the problem with the Nuget package an issue on your end or was it because of my stupidity?

This solves my problems with the Nuget packages and should be good to merge.

PS: I'm surprised you found the exact project I'm working on. :)

**Comment by kasmacioma** [comment]
> Was the problem with the Nuget package an issue on your end or was it because of my stupidity?

It was because of my stupidity as my script took version from generating package, not dependency one.

**Review by LumpBloom7 — APPROVED** [review]
That would work as well.

Thanks again.

**Comment by LumpBloom7** [comment]
Merging this pull request as it seems complete.

**Comment by LumpBloom7** [comment]
Shit. Noticed that dynamic linking is not used on all build configurations. Will fix in seperate commit.

**Pull request merged**
